version: '3'

services:
  postgres:
    container_name: valida_server
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ra1205
      POSTGRES_DB: valida_server_db
      PGDATA: /data/postgres
    volumes:
      - /data/pg:/data/postgres
